In [81]:
import pandas as pd
import numpy as np

# Dealing with the data

In [82]:
data = pd.read_csv('bodyfat.csv')
data.shape
data.head()

,Density,BodyFat,Age,Weight,Height,Neck,Chest,Abdomen,Hip,Thigh,Knee,Ankle,Biceps,Forearm,Wrist
0,1.0708,12.3,23,154.25,67.75,36.2,93.1,85.2,94.5,59.0,37.3,21.9,32.0,27.4,17.1
1,1.0853,6.1,22,173.25,72.25,38.5,93.6,83.0,98.7,58.7,37.3,23.4,30.5,28.9,18.2
2,1.0414,25.3,22,154.00,66.25,34.0,95.8,87.9,99.2,59.6,38.9,24.0,28.8,25.2,16.6
3,1.0751,10.4,26,184.75,72.25,37.4,101.8,86.4,101.2,60.1,37.3,22.8,32.4,29.4,18.2
4,1.0340,28.7,24,184.25,71.25,34.4,97.3,100.0,101.9,63.2,42.2,24.0,32.2,27.7,17.7

In [83]:
#Standardize header names.
def coloumn_names_lwr(data):
    data.columns = map(str.lower, data.columns)
    data.head()
    #data.columns = [x.lower() for x in data.columns]
    
def coloumn_names_captl(data):
    data.columns = map(str.capitalize, data.columns)
    data.head()
    #data.columns = [x.capitalize() for x in data.columns]

In [ ]:
def check_missing_data(data):
    print(data.isna().sum())

#def check_missing_values(data)

In [88]:
#numercial and categorical data

numerical_values = pd.DataFrame()
continuous_values = pd.DataFrame()
categorical_values = pd.DataFrame()

def check_dataypes(data):
    numerical = data.select_dtypes(np.number)
    numerical_continuous = data.select_dtypes(include=['float64'])
    categorical = data.select_dtypes(object)
    return numerical,numerical_continuous,categorical

density    0
bodyfat    0
age        0
weight     0
height     0
neck       0
chest      0
abdomen    0
hip        0
thigh      0
knee       0
ankle      0
biceps     0
forearm    0
wrist      0
dtype: int64

Omitting the density coloumn on purpose because to predict the body fat percentage of a person based on the circumferential measurements already available, which is good enough to predict with so much available data.

I will, create Model only with these data, and predict again with my personal data set for the information randomly to validate the model.

Fat (%) = [(4*95/density) -4.51 x 100]

source:https://www.cambridge.org/core/services/aop-cambridge-core/content/view/DA80501B784742B9B2F4F454BDEE923B/S0007114567000728a.pdf/the-assessment-of-the-amount-of-fat-in-the-human-body-from-measurements-of-skinfold-thickness.pdf

# Exploring the data

In [85]:
#converting the dataset to metric system
def convert_weight_kg(data):
    data['weight']=data['weight'].apply(lambda x : round((x * 0.453),2))
    
def convert_inch_to_cm(data):
    #drop weight, density and body fat percentage
    # 12 inches --> 30 cm
    #formula X cm = [30/12] * input inches
    df_drops = data[['density','bodyfat','age','weight']]
    df2 = data.drop(['density','bodyfat','age','weight'], axis=1)
    df2 = df2.apply(lambda x : x * 2.5)
    data = pd.concat([df_drops, df2], axis=1, join="outer")
    #data = data.merge(df2)
    return data

In [86]:
pd.set_option('display.max_columns', None)

In [87]:
# Fucntion calls and declarations
numerical_values = pd.DataFrame()
continuous_values = pd.DataFrame()
categorical_values = pd.DataFrame()
coloumn_names_lwr(data)
numerical_values,continuous_values,categorical_values = check_dataypes(data)
convert_weight_kg(data)
convert_inch_to_cm(data)

data2.head(10)
#numerical_values.head(20)

,density,bodyfat,age,weight,height,neck,chest,abdomen,hip,thigh,knee,ankle,biceps,forearm,wrist
0,1.0708,12.3,23,69.88,169.375,90.50,232.75,213.00,236.25,147.50,93.25,54.75,80.00,68.50,42.75
1,1.0853,6.1,22,78.48,180.625,96.25,234.00,207.50,246.75,146.75,93.25,58.50,76.25,72.25,45.50
2,1.0414,25.3,22,69.76,165.625,85.00,239.50,219.75,248.00,149.00,97.25,60.00,72.00,63.00,41.50
3,1.0751,10.4,26,83.69,180.625,93.50,254.50,216.00,253.00,150.25,93.25,57.00,81.00,73.50,45.50
4,1.0340,28.7,24,83.47,178.125,86.00,243.25,250.00,254.75,158.00,105.50,60.00,80.50,69.25,44.25
5,1.0502,20.9,24,95.24,186.875,97.50,261.25,236.00,269.50,165.00,105.00,64.00,89.25,76.50,47.00
6,1.0549,19.2,26,81.99,174.375,91.00,262.75,226.75,250.75,146.00,95.75,57.25,79.75,69.50,44.25
7,1.0704,12.4,25,79.73,181.250,94.50,249.00,221.25,242.75,150.00,98.50,58.00,76.25,72.50,47.00
8,1.0900,4.1,25,86.52,185.000,95.25,252.25,206.25,249.75,157.25,95.75,59.50,89.75,77.75,45.50
9,1.0722,11.7,23,89.81,183.750,105.25,249.00,221.50,260.25,157.75,104.25,62.50,89.00,75.00,48.00